import { describe, expect, it, vi } from 'vitest';
import { withUniqueCode } from '@server/services/codes';

/**
 * Record codes are generated by reading the highest one and adding one, which
 * two simultaneous creations both do before either commits. It surfaced as a
 * raw "Unique constraint failed on Project_code_key" — first from two test
 * files running in parallel, but two salespeople clicking "create" together is
 * the same event.
 */
const collision = (target: string | string[] = ['code']) =>
  Object.assign(new Error('Unique constraint failed'), { code: 'P2002', meta: { target } });

describe('withUniqueCode', () => {
  it('returns the first success without retrying', async () => {
    const create = vi.fn().mockResolvedValue('ok');
    await expect(withUniqueCode(create)).resolves.toBe('ok');
    expect(create).toHaveBeenCalledTimes(1);
  });

  it('retries a code collision and succeeds on the next attempt', async () => {
    const create = vi.fn().mockRejectedValueOnce(collision()).mockResolvedValue('ok');
    await expect(withUniqueCode(create)).resolves.toBe('ok');
    expect(create).toHaveBeenCalledTimes(2);
  });

  it('recomputes on every attempt rather than replaying the losing value', async () => {
    // The point of passing a function: attempt two must read the maximum again.
    let next = 1;
    const create = vi.fn(async () => {
      const code = `P-${next}`;
      next += 1;
      if (code === 'P-1') throw collision();
      return code;
    });
    await expect(withUniqueCode(create)).resolves.toBe('P-2');
  });

  it('gives up after the attempt limit rather than looping forever', async () => {
    const create = vi.fn().mockRejectedValue(collision());
    await expect(withUniqueCode(create, 3)).rejects.toMatchObject({ code: 'P2002' });
    expect(create).toHaveBeenCalledTimes(3);
  });

  it('does not retry a conflict with the data itself', async () => {
    // A duplicate email is a real conflict. Retrying it fails five times
    // slower and reports the same thing.
    const create = vi.fn().mockRejectedValue(collision(['email']));
    await expect(withUniqueCode(create)).rejects.toMatchObject({ code: 'P2002' });
    expect(create).toHaveBeenCalledTimes(1);
  });

  it('does not swallow an unrelated failure', async () => {
    const create = vi.fn().mockRejectedValue(new Error('database is on fire'));
    await expect(withUniqueCode(create)).rejects.toThrow('database is on fire');
    expect(create).toHaveBeenCalledTimes(1);
  });
});
