/**
 * Human-facing record codes (`C-000001`, `P-000001`).
 *
 * These are generated by reading the highest existing code and adding one,
 * which is racy: two people creating a project in the same moment both read
 * the same maximum and one of them collides on the unique index. It surfaced
 * as a raw `Unique constraint failed on Project_code_key`, and it is not a
 * test-only problem — two salespeople clicking "create" together is an
 * ordinary Tuesday.
 *
 * A Postgres sequence would remove the race outright, and would be the right
 * answer if these codes came only from this application. They do not: existing
 * records may be imported with codes already assigned, and a sequence that
 * does not know about them starts handing out duplicates. Reading the maximum
 * tolerates that; retrying makes it safe.
 *
 * Retry rather than a lock because the collision is rare and the work is
 * cheap. A lock would serialise every creation in the system to protect
 * against something that happens when two clicks land in the same
 * millisecond.
 */

/** Prisma's unique-constraint violation. */
const UNIQUE_VIOLATION = 'P2002';

function isCodeCollision(err: unknown): boolean {
  if (!err || typeof err !== 'object') return false;
  const e = err as { code?: unknown; meta?: { target?: unknown } };
  if (e.code !== UNIQUE_VIOLATION) return false;

  // Only a collision on the code column is safe to retry. A duplicate email is
  // a real conflict with the data, and retrying it would just fail five times
  // slower before reporting the same thing.
  const target = e.meta?.target;
  const text = Array.isArray(target) ? target.join(',') : String(target ?? '');
  return text.toLowerCase().includes('code');
}

/**
 * Run `create`, retrying while it loses a race for the next code.
 *
 * `create` must generate the code itself on each attempt — passing a
 * pre-computed one in would retry the same losing value.
 */
export async function withUniqueCode<T>(create: () => Promise<T>, attempts = 5): Promise<T> {
  let lastError: unknown;
  for (let i = 0; i < attempts; i += 1) {
    try {
      return await create();
    } catch (err) {
      if (!isCodeCollision(err)) throw err;
      lastError = err;
    }
  }
  throw lastError;
}
