/**
 * Write the list of migrations this build expects into a source file.
 *
 * The application cannot read `prisma/migrations` at runtime — the directory is
 * not part of a serverless bundle — but it can compare a compiled-in list
 * against what the database says it has applied. That turns "migrations were
 * never run against production" from an obscure foreign-key error at the moment
 * an operator clicks delete into a line on the system health page.
 *
 * It happened twice: once on the first deployment, once after a schema change.
 * A deploy step that has to be remembered will eventually be forgotten.
 */
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migrationsDir = join(root, 'prisma', 'migrations');
const outFile = join(root, 'src', 'generated', 'migrations.ts');

const names = readdirSync(migrationsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// Generated by scripts/generate-migration-manifest.ts — do not edit.\n` +
    `// Regenerated on every build; committed so a checkout typechecks without one.\n` +
    `export const EXPECTED_MIGRATIONS: readonly string[] = [\n` +
    names.map((n) => `  '${n}',`).join('\n') +
    `\n];\n`,
  'utf8',
);

console.log(`migration manifest: ${names.length} migrations`);
